name: Cypress Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Cypress Test
      uses: cypress-io/github-action@v5
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: C:\Users\GAFAR\Documents\GIT\g-repo\package-lock.json
        build: npm run build
        start: job
